import type { Logger } from '../utils/logger.util';

/**
 * Augments Express's Request interface with ITMS-specific properties
 * attached by middleware (logging, auth).
 *
 * This file must be a module (has exports) for the declaration merging to work.
 */
declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Express {
    interface Request {
      /** Unique correlation ID generated by loggingMiddleware (format: req_*) */
      id: string;

      /** Structured logger scoped to the request path */
      logger: Logger;

      /** Authenticated user — populated by authMiddleware after JWT validation */
      user?: {
        id: string;
        email: string;
        role: 'user' | 'admin';
      };
    }
  }
}

export {};
